### ISSUE TITLE
suggestion: get rid of the `grails-app/vaadin` directory with 7.3

### ISSUE THREAD

**Issue by christoph-frick** [ondrej-kvasnovsky/grails-vaadin-plugin#38]
With the major change in version I want to throw in some food for thoughts.  what about getting rid of the `grails-app/vaadin` directory.  all dirs under `grails-app` are there because of "convention over configuration".  so placing something there would imply, that some magic is happening with the files there.  but to my knowledge, this is not the case. so my suggestion would be to get rid of the handling of this directory and let the users put their code just into `src/(groovy|java)` as always.

**Comment by Tonix-Tuft** [comment]
Hi, could you please link us a reference where you explain how to create a grails project with the vaadin plugin integrated now that the "grails install-plugin" is deprecated? What are the steps? Add a `compile ":vaadin:7.3.9"` instruction inside BuildConfig.groovy and then run the `grails> compile` target?

Now that `grails-app/vaadin` folder is not created anymore, where is the auto created UI code put?

**Comment by ondrej-kvasnovsky** [comment]
Hi, 

we get rid of vaadin folder and we use src/groovy folder instead. Where have you find old approach? Currently, I only keep https://www.gitbook.com/book/ondrej-kvasnovsky/vaadin-on-grails/dashboard updated. Probably I forgot other places to update... 

Yes, adding compile ":vaadin:7.3.9" into BuildConfig.groovy is all you need to do. If you want to generate code to create a sample application to start with, use "grails vaadin-quickstart". More info is here: https://github.com/ondrej-kvasnovsky/grails-vaadin-plugin/issues/39

**Comment by Tonix-Tuft** [comment]
Hi Ondřej,

thank you for your response!
Here are the links:
- on the grails.org page of the plugin -> http://grails.org/plugin/vaadin
there's this link -> where the old approach with the usage of the
`grails-app/vaadin` folder is applied;
- on this page ->
http://ondrej-kvasnovsky.blogspot.ru/2012/03/vaadin-and-grails-part-i-hello-world.html
you use the Grails Plugin Manager tool to install the plugin but it doesn't
work on my eclipse because the "Continue" button is disabled;

Also, as I said, inside the Vaadin 7 CookBook in* Chapter 1 - Running
Vaadin on Grails* the old approach (`grails install-plugin`) is used.

I added the `compile ":vaadin:7.3.9"` entry inside BuildConfig.groovy, then
I run the `grails compile` command and after that I tried to type the
command `grails vaadin-quickstart` you advised me, the app.MyUI.groovy
class is created, but the problem now is that Grails complains about the
Vaadin's classes (UI, VaadinRequest, and so on...) saying that they can't
be resolved to a type.

It seems that Grails doesn't see the Vaadin plugin:


​

I am sorry for bothering you again, but could you please advise me what can
I do in order to resolve this issue?

Thank you again for your attention!

Best regards,
Anton.


2015-01-30 19:57 GMT+03:00 Ondrej Kvasnovsky <notifications@github.com>:

**Comment by christoph-frick** [comment]
@Tonix-Tuft just for the records: install-plugin got killed in grails long time ago.  you will see the "old" way for many other plugins around.  and for the error there: have you done a `grails package` or told your IDE to refresh the deps?

**Comment by Tonix-Tuft** [comment]
@christoph-frick  This was my first day of Grails! Wow, I finally setup a working Grails project with Vaadin, thank you @ondrej-kvasnovsky, @christoph-frick, the Grails Tools -> Refresh Dependencies like you told has worked for me!

**Comment by ondrej-kvasnovsky** [comment]
Yes, the biggest trick every for Grails applications, "Refresh Dependencies".  I am glad you set it up.

**Comment by Tonix-Tuft** [comment]
Thank you Ondrej and thank you Christoph, moving on forward with the book!



2015-02-01 9:59 GMT+03:00 Ondrej Kvasnovsky <notifications@github.com>:
