### ISSUE TITLE
ERROR context.GrailsContextLoaderListener  - Error initializing the application: Error creating bean with name 'transactionManagerPostProcessor': Initialization of bean failed; in a newly created Grails project with Vaadin plugin 7.3.9

### ISSUE THREAD

**Issue by Tonix-Tuft** [ondrej-kvasnovsky/grails-vaadin-plugin#48]
Hi,

I get the following error each time I create a new Grails project in Eclipse with the Vaadin 7.3.9 Grails plugin:

```
|Running Grails application
objc[8673]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/bin/java and /Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre/lib/libinstrument.dylib. One of the two will be used. Which one is undefined.
| Error 2015-03-05 15:33:52,173 [localhost-startStop-1] ERROR context.GrailsContextLoaderListener  - Error initializing the application: Error creating bean with name 'transactionManagerPostProcessor': Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'transactionManager': Cannot resolve reference to bean 'sessionFactory' while setting bean property 'sessionFactory'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sessionFactory': Invocation of init method failed; nested exception is org.hibernate.cfg.beanvalidation.IntegrationException: Error activating Bean Validation integration
Message: Error creating bean with name 'transactionManagerPostProcessor': Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'transactionManager': Cannot resolve reference to bean 'sessionFactory' while setting bean property 'sessionFactory'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sessionFactory': Invocation of init method failed; nested exception is org.hibernate.cfg.beanvalidation.IntegrationException: Error activating Bean Validation integration
    Line | Method
->>  266 | run       in java.util.concurrent.FutureTask
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
|   1142 | runWorker in java.util.concurrent.ThreadPoolExecutor
|    617 | run . . . in java.util.concurrent.ThreadPoolExecutor$Worker
^    745 | run       in java.lang.Thread
Caused by BeanCreationException: Error creating bean with name 'transactionManager': Cannot resolve reference to bean 'sessionFactory' while setting bean property 'sessionFactory'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sessionFactory': Invocation of init method failed; nested exception is org.hibernate.cfg.beanvalidation.IntegrationException: Error activating Bean Validation integration
->>  266 | run       in java.util.concurrent.FutureTask
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
|   1142 | runWorker in java.util.concurrent.ThreadPoolExecutor
|    617 | run . . . in java.util.concurrent.ThreadPoolExecutor$Worker
^    745 | run       in java.lang.Thread
Caused by BeanCreationException: Error creating bean with name 'sessionFactory': Invocation of init method failed; nested exception is org.hibernate.cfg.beanvalidation.IntegrationException: Error activating Bean Validation integration
->>  266 | run       in java.util.concurrent.FutureTask
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
|   1142 | runWorker in java.util.concurrent.ThreadPoolExecutor
|    617 | run . . . in java.util.concurrent.ThreadPoolExecutor$Worker
^    745 | run       in java.lang.Thread
Caused by IntegrationException: Error activating Bean Validation integration
->>  266 | run       in java.util.concurrent.FutureTask
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
|   1142 | runWorker in java.util.concurrent.ThreadPoolExecutor
|    617 | run . . . in java.util.concurrent.ThreadPoolExecutor$Worker
^    745 | run       in java.lang.Thread
Caused by NoClassDefFoundError: javax/validation/ParameterNameProvider
->>  760 | defineClass in java.lang.ClassLoader
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
|    142 | defineClass in java.security.SecureClassLoader
|    455 | defineClass in java.net.URLClassLoader
|     73 | access$100 in     ''
|    367 | run . . . in java.net.URLClassLoader$1
|    361 | run       in     ''
|    360 | findClass in java.net.URLClassLoader
|    424 | loadClass in java.lang.ClassLoader
|    269 | configure in javax.validation.Validation$GenericBootstrapImpl
|    111 | buildDefaultValidatorFactory in javax.validation.Validation
|    266 | run . . . in java.util.concurrent.FutureTask
|   1142 | runWorker in java.util.concurrent.ThreadPoolExecutor
|    617 | run . . . in java.util.concurrent.ThreadPoolExecutor$Worker
^    745 | run       in java.lang.Thread
Caused by ClassNotFoundException: javax.validation.ParameterNameProvider
->>  372 | run       in java.net.URLClassLoader$1
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
|    361 | run       in     ''
|    360 | findClass in java.net.URLClassLoader
|    424 | loadClass in java.lang.ClassLoader
|    760 | defineClass in     ''
|    142 | defineClass in java.security.SecureClassLoader
|    455 | defineClass in java.net.URLClassLoader
|     73 | access$100 in     ''
|    367 | run . . . in java.net.URLClassLoader$1
|    361 | run       in     ''
|    360 | findClass in java.net.URLClassLoader
|    424 | loadClass in java.lang.ClassLoader
|    269 | configure in javax.validation.Validation$GenericBootstrapImpl
|    111 | buildDefaultValidatorFactory in javax.validation.Validation
|    266 | run . . . in java.util.concurrent.FutureTask
|   1142 | runWorker in java.util.concurrent.ThreadPoolExecutor
|    617 | run . . . in java.util.concurrent.ThreadPoolExecutor$Worker
^    745 | run       in java.lang.Thread
Error |
Forked Grails VM exited with error
```

I have created a Grails project using the Eclipse wizard (Grails version 2.4.4).

Then installed the vaadin grails plugin, added `compile ":vaadin:7.3.9"` inside `BuildConfig.groovy`, recompiled with `grails compile` and refreshed the dependencies with `Grails Tools -> Refresh Dependencies`.

After that, when I run the application with `grails run-app` or `grails dev run-app`, I get the error above.

Is there a way to resolve?

**Comment by zhuravskiy** [comment]
Hi. You problem in "Caused by ClassNotFoundException: javax.validation.ParameterNameProvider"
Please, see http://stackoverflow.com/questions/16163162/vaadin-7-bean-validation

**Comment by Tonix-Tuft** [comment]
All right, but I haven't add any dependency, only the `compile ":vaadin:7.3.9"` line inside BuildConfig.groovy, compiled, refreshed and then the error starts to appear. Could you please advise me what could I do in order to fix? Add a Bean Validation API `validation-api`? Where?

**Comment by Tonix-Tuft** [comment]
I have found with `grails dependency-report` that my project is using `hibernate-validator-.5.1.1.Final` and the vaadin plugin for grails comes with `validation-api.1.0.0.GA` which seems to cause the error as `hibernate-validator-.5.1.1.Final` does not support  validation-api.1.0.0, therefore I tried to downgrade to `hibernate-validator-4.1.0.Final` by using "Hibernate 3 for Grails" instead of hibernate4 (`runtime ":hibernate:3.6.10.18"` instead of `":hibernate4:4.3.6.1"` inside BuildConfig.groovy), refreshed the dependencies, compiled, but again when I start the application, I get the same error.

Is there a way to resolve once for all?

**Comment by sascha-frinken** [comment]
Just a shot in the dark...
Try to add this into your  _Events.groovy script:
```
ant.delete(dir:"${stagingDir}/WEB-INF/lib/", includes: "hibernate-validator-.5.1.1*.jar", verbose: true)
```

HTH

**Comment by Tonix-Tuft** [comment]
Inside `./project-root/target/work/plugins/vaadin-7.3.9/scripts/_Events.groovy`? Sorry, I have tried but it still doesn't work, same issue `Caused by NoClassDefFoundError: javax/validation/ParameterNameProvider`, is there anything else I could try?

**Comment by sascha-frinken** [comment]
Could you post your BuildConfig.groovy?

**Comment by Tonix-Tuft** [comment]
Yes, here it is (the only thing I added was `compile ":vaadin:7.3.9"` inside `plugins`):
```
grails.servlet.version = "3.0" // Change depending on target container compliance (2.5 or 3.0)
grails.project.class.dir = "target/classes"
grails.project.test.class.dir = "target/test-classes"
grails.project.test.reports.dir = "target/test-reports"
grails.project.work.dir = "target/work"
grails.project.target.level = 1.6
grails.project.source.level = 1.6
//grails.project.war.file = "target/${appName}-${appVersion}.war"

grails.project.fork = [
    // configure settings for compilation JVM, note that if you alter the Groovy version forked compilation is required
    //  compile: [maxMemory: 256, minMemory: 64, debug: false, maxPerm: 256, daemon:true],

    // configure settings for the test-app JVM, uses the daemon by default
    test: [maxMemory: 768, minMemory: 64, debug: false, maxPerm: 256, daemon:true],
    // configure settings for the run-app JVM
    run: [maxMemory: 768, minMemory: 64, debug: false, maxPerm: 256, forkReserve:false],
    // configure settings for the run-war JVM
    war: [maxMemory: 768, minMemory: 64, debug: false, maxPerm: 256, forkReserve:false],
    // configure settings for the Console UI JVM
    console: [maxMemory: 768, minMemory: 64, debug: false, maxPerm: 256]
]

grails.project.dependency.resolver = "maven" // or ivy
grails.project.dependency.resolution = {
    // inherit Grails' default dependencies
    inherits("global") {
        // specify dependency exclusions here; for example, uncomment this to disable ehcache:
        // excludes 'ehcache'
    }
    log "error" // log level of Ivy resolver, either 'error', 'warn', 'info', 'debug' or 'verbose'
    checksums true // Whether to verify checksums on resolve
    legacyResolve false // whether to do a secondary resolve on plugin installation, not advised and here for backwards compatibility

    repositories {
        inherits true // Whether to inherit repository definitions from plugins

        grailsPlugins()
        grailsHome()
        mavenLocal()
        grailsCentral()
        mavenCentral()
        // uncomment these (or add new ones) to enable remote dependency resolution from public Maven repositories
        //mavenRepo "http://repository.codehaus.org"
        //mavenRepo "http://download.java.net/maven/2/"
        //mavenRepo "http://repository.jboss.com/maven2/"
    }

    dependencies {
        // specify dependencies here under either 'build', 'compile', 'runtime', 'test' or 'provided' scopes e.g.
        // runtime 'mysql:mysql-connector-java:5.1.29'
        // runtime 'org.postgresql:postgresql:9.3-1101-jdbc41'
        test "org.grails:grails-datastore-test-support:1.0.2-grails-2.4"
    }

    plugins {
        // plugins for the build system only
        build ":tomcat:7.0.55"

        // plugins for the compile step
        compile ":scaffolding:2.1.2"
        compile ':cache:1.1.8'
        compile ":asset-pipeline:1.9.9"
		compile ":vaadin:7.3.9"

        // plugins needed at runtime but not for compilation		        
        runtime ":hibernate4:4.3.6.1" // or ":hibernate:3.6.10.18"									   
        runtime ":database-migration:1.4.0"
        runtime ":jquery:1.11.1"
		
        // Uncomment these to enable additional asset-pipeline capabilities
        //compile ":sass-asset-pipeline:1.9.0"
        //compile ":less-asset-pipeline:1.10.0"
        //compile ":coffee-asset-pipeline:1.8.0"
        //compile ":handlebars-asset-pipeline:1.3.0.3"
    }
}
```

**Comment by sascha-frinken** [comment]
Hmm, The only difference I see is the hibernate version I am running: 
runtime ":hibernate4:4.3.5.5"
Maybe you want to try with this version... Before you start, run: 
```
grails clean-all
grails package
```

**Comment by Tonix-Tuft** [comment]
It worked, thank you very much!!! Do you have any idea on why does the plugin doesn't like ":hibernate4:4.3.6.1" or ":hibernate:3.6.10.18"? 

Can I set up Eclipse/Grails so that it creates the project with the same ":hibernate4:4.3.5.5" plugin you use and which works (so that I don't have to always remember this and manually change it)?

**Comment by ondrej-kvasnovsky** [comment]
As far as I know, it is not possible to configure Grails nor Eclipse like that.

**Comment by sanjay-mrk** [comment]
Hi,

I am getting the following error while change the Oracle database version from 11g to 19c Even I have upgrade the OJDBC6 to OJDBC7 hence it partially supports the Oracle 19c. 
Even though I am facing these errors.

Configuring Shiro ...
03-06@06:42:335422 INFO  [localhost-startStop-1]                     ShiroGrailsPlugin     - Registering realm: simplica.user.UserRealm
03-06@06:42:356956 INFO  [localhost-startStop-1]         org.hibernate.cfg.Environment     - Hibernate 3.6.10.Final
03-06@06:42:356956 INFO  [localhost-startStop-1]         org.hibernate.cfg.Environment     - hibernate.properties not found
03-06@06:42:356971 INFO  [localhost-startStop-1]         org.hibernate.cfg.Environment     - Bytecode provider name : javassist
03-06@06:42:356971 INFO  [localhost-startStop-1]         org.hibernate.cfg.Environment     - using JDK 1.4 java.sql.Timestamp handling
03-06@06:42:356971 WARN  [localhost-startStop-1] org.hibernate.dialect.resolver.StandardDialectResolver     - unknown Oracle major version [19]
03-06@06:42:357003 ERROR [localhost-startStop-1] org.codehaus.groovy.grails.web.context.GrailsContextLoader     - Error initializing the application: Error creating bean with name 'transactionManagerPostProcessor': Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'transactionManager': Cannot resolve reference to bean 'sessionFactory' while setting bean property 'sessionFactory'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sessionFactory': Cannot resolve reference to bean 'hibernateProperties' while setting bean property 'hibernateProperties'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'hibernateProperties': Cannot resolve reference to bean 'dialectDetector' while setting bean property 'properties' with key [hibernate.dialect]; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dialectDetector': Invocation of init method failed; nested exception is org.codehaus.groovy.grails.orm.hibernate.exceptions.CouldNotDetermineHibernateDialectException: Could not determine Hibernate dialect for database name [Oracle]!
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'transactionManagerPostProcessor': Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'transactionManager': Cannot resolve reference to bean 'sessionFactory' while setting bean property 'sessionFactory'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sessionFactory': Cannot resolve reference to bean 'hibernateProperties' while setting bean property 'hibernateProperties'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'hibernateProperties': Cannot resolve reference to bean 'dialectDetector' while setting bean property 'properties' with key [hibernate.dialect]; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dialectDetector': Invocation of init method failed; nested exception is org.codehaus.groovy.grails.orm.hibernate.exceptions.CouldNotDetermineHibernateDialectException: Could not determine Hibernate dialect for database name [Oracle]!
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'transactionManager': Cannot resolve reference to bean 'sessionFactory' while setting bean property 'sessionFactory'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sessionFactory': Cannot resolve reference to bean 'hibernateProperties' while setting bean property 'hibernateProperties'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'hibernateProperties': Cannot resolve reference to bean 'dialectDetector' while setting bean property 'properties' with key [hibernate.dialect]; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dialectDetector': Invocation of init method failed; nested exception is org.codehaus.groovy.grails.orm.hibernate.exceptions.CouldNotDetermineHibernateDialectException: Could not determine Hibernate dialect for database name [Oracle]!
	... 4 more
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sessionFactory': Cannot resolve reference to bean 'hibernateProperties' while setting bean property 'hibernateProperties'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'hibernateProperties': Cannot resolve reference to bean 'dialectDetector' while setting bean property 'properties' with key [hibernate.dialect]; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dialectDetector': Invocation of init method failed; nested exception is org.codehaus.groovy.grails.orm.hibernate.exceptions.CouldNotDetermineHibernateDialectException: Could not determine Hibernate dialect for database name [Oracle]!
	... 4 more
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'hibernateProperties': Cannot resolve reference to bean 'dialectDetector' while setting bean property 'properties' with key [hibernate.dialect]; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dialectDetector': Invocation of init method failed; nested exception is org.codehaus.groovy.grails.orm.hibernate.exceptions.CouldNotDetermineHibernateDialectException: Could not determine Hibernate dialect for database name [Oracle]!
	... 4 more
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dialectDetector': Invocation of init method failed; nested exception is org.codehaus.groovy.grails.orm.hibernate.exceptions.CouldNotDetermineHibernateDialectException: Could not determine Hibernate dialect for database name [Oracle]!
	... 4 more
Caused by: org.codehaus.groovy.grails.orm.hibernate.exceptions.CouldNotDetermineHibernateDialectException: Could not determine Hibernate dialect for database name [Oracle]!
	... 4 more

Process finished with exit code 1
