### ISSUE TITLE
Failed to create comet support class

### ISSUE THREAD

**Issue by wehe64** [ondrej-kvasnovsky/grails-vaadin-plugin#61]
I can't get the grails3 version starting up the server propperly - on `run-app` I get:
```
o.a.cpr.DefaultAsyncSupportResolver      : Failed to create comet support class: class org.atmosphere.container.JettyServlet30AsyncSupportWithWebSocket, error: null
o.a.cpr.DefaultAsyncSupportResolver      : Switching to BlockingIO

```
and http://localhost:8080/VAADIN/widgetsets/app.widgetset/app.widgetset.nocache.js?1486396385691
ends up with a 404.

seems related to https://github.com/Atmosphere/atmosphere/issues/912
happens once I add my UI-subclass to the project.

BTW, thanks so much for the plugin, guys! 
weHe
[failcase.zip](https://github.com/ondrej-kvasnovsky/grails-vaadin-plugin/files/755203/failcase.zip)

**Comment by ondrej-kvasnovsky** [comment]
These are two separate issues (I think). 

**First one widgetset with 404:** 
You need to open VaadinConfig.groovy and comment out row with "widgetset = 'app.widgetset'". Because Vaadin is trying to find that widget set (but you have none). 

**Second issue, Failed to create comet support class: class org.atmosphere.container.JettyServlet30AsyncSupportWithWebSocket**
This one, it is first time I see that. It seems it does not have any influence on the running app (but we should solve that).
